package com.event.entry;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_account.account_no
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String accountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_account.account_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_account.account_status
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private Boolean accountStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_account.account_no
     *
     * @return the value of er_account.account_no
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_account.account_no
     *
     * @param accountNo the value for er_account.account_no
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_account.account_name
     *
     * @return the value of er_account.account_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_account.account_name
     *
     * @param accountName the value for er_account.account_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_account.account_status
     *
     * @return the value of er_account.account_status
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public Boolean getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_account.account_status
     *
     * @param accountStatus the value for er_account.account_status
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setAccountStatus(Boolean accountStatus) {
        this.accountStatus = accountStatus;
    }

    @Override
    public String toString() {
        return "Account{" +
                "accountNo='" + accountNo + '\'' +
                ", accountName='" + accountName + '\'' +
                ", accountStatus=" + accountStatus +
                '}';
    }
}