package com.event.entry;

public class EventPoint extends EventPointKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event_point.event_point_content
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String eventPointContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event_point.event_point_begin
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String eventPointBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event_point.event_point_end
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String eventPointEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event_point.event_point_content
     *
     * @return the value of er_event_point.event_point_content
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getEventPointContent() {
        return eventPointContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event_point.event_point_content
     *
     * @param eventPointContent the value for er_event_point.event_point_content
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventPointContent(String eventPointContent) {
        this.eventPointContent = eventPointContent == null ? null : eventPointContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event_point.event_point_begin
     *
     * @return the value of er_event_point.event_point_begin
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getEventPointBegin() {
        return eventPointBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event_point.event_point_begin
     *
     * @param eventPointBegin the value for er_event_point.event_point_begin
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventPointBegin(String eventPointBegin) {
        this.eventPointBegin = eventPointBegin == null ? null : eventPointBegin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event_point.event_point_end
     *
     * @return the value of er_event_point.event_point_end
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getEventPointEnd() {
        return eventPointEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event_point.event_point_end
     *
     * @param eventPointEnd the value for er_event_point.event_point_end
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventPointEnd(String eventPointEnd) {
        this.eventPointEnd = eventPointEnd == null ? null : eventPointEnd.trim();
    }
}