package com.event.entry;

public class EventPointKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event_point.account_event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String accountEventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event_point.event_ponit_order
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private Integer eventPonitOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event_point.event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String eventId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event_point.account_event_id
     *
     * @return the value of er_event_point.account_event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getAccountEventId() {
        return accountEventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event_point.account_event_id
     *
     * @param accountEventId the value for er_event_point.account_event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setAccountEventId(String accountEventId) {
        this.accountEventId = accountEventId == null ? null : accountEventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event_point.event_ponit_order
     *
     * @return the value of er_event_point.event_ponit_order
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public Integer getEventPonitOrder() {
        return eventPonitOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event_point.event_ponit_order
     *
     * @param eventPonitOrder the value for er_event_point.event_ponit_order
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventPonitOrder(Integer eventPonitOrder) {
        this.eventPonitOrder = eventPonitOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event_point.event_id
     *
     * @return the value of er_event_point.event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event_point.event_id
     *
     * @param eventId the value for er_event_point.event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }
}