package com.event.entry;

public class EventKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event.event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event.event_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String eventName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event.event_id
     *
     * @return the value of er_event.event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event.event_id
     *
     * @param eventId the value for er_event.event_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventId(String eventId) {
        this.eventId = eventId == null ? null : eventId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event.event_name
     *
     * @return the value of er_event.event_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event.event_name
     *
     * @param eventName the value for er_event.event_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }
}