package com.event.entry;

public class Event extends EventKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event.event_type
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private byte[] eventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_event.event_description
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String eventDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event.event_type
     *
     * @return the value of er_event.event_type
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public byte[] getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event.event_type
     *
     * @param eventType the value for er_event.event_type
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventType(byte[] eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_event.event_description
     *
     * @return the value of er_event.event_description
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getEventDescription() {
        return eventDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_event.event_description
     *
     * @param eventDescription the value for er_event.event_description
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription == null ? null : eventDescription.trim();
    }
}