package com.event.entry;

public class UserIdentity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_user_identity.user_identity_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String userIdentityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_user_identity.user_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_user_identity.user_age
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column er_user_identity.user_sex
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    private Boolean userSex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_user_identity.user_identity_id
     *
     * @return the value of er_user_identity.user_identity_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getUserIdentityId() {
        return userIdentityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_user_identity.user_identity_id
     *
     * @param userIdentityId the value for er_user_identity.user_identity_id
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setUserIdentityId(String userIdentityId) {
        this.userIdentityId = userIdentityId == null ? null : userIdentityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_user_identity.user_name
     *
     * @return the value of er_user_identity.user_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_user_identity.user_name
     *
     * @param userName the value for er_user_identity.user_name
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_user_identity.user_age
     *
     * @return the value of er_user_identity.user_age
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_user_identity.user_age
     *
     * @param userAge the value for er_user_identity.user_age
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column er_user_identity.user_sex
     *
     * @return the value of er_user_identity.user_sex
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public Boolean getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column er_user_identity.user_sex
     *
     * @param userSex the value for er_user_identity.user_sex
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    public void setUserSex(Boolean userSex) {
        this.userSex = userSex;
    }
}