package com.event.dao;

import com.event.entry.AccountEventKey;

public interface AccountEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int deleteByPrimaryKey(AccountEventKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insert(AccountEventKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insertSelective(AccountEventKey record);
}