package com.event.dao;

import com.event.entry.Account;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int deleteByPrimaryKey(String accountNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    Account selectByPrimaryKey(String accountNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_account
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int updateByPrimaryKey(Account record);
}