package com.event.dao;

import com.event.entry.Event;
import com.event.entry.EventKey;

public interface EventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int deleteByPrimaryKey(EventKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insert(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insertSelective(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    Event selectByPrimaryKey(EventKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int updateByPrimaryKeySelective(Event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_event
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int updateByPrimaryKey(Event record);
}