package com.event.dao;

import com.event.entry.UserIdentity;

public interface UserIdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_user_identity
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int deleteByPrimaryKey(String userIdentityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_user_identity
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insert(UserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_user_identity
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int insertSelective(UserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_user_identity
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    UserIdentity selectByPrimaryKey(String userIdentityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_user_identity
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int updateByPrimaryKeySelective(UserIdentity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table er_user_identity
     *
     * @mbg.generated Sun Oct 25 02:25:26 CST 2020
     */
    int updateByPrimaryKey(UserIdentity record);
}